//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRD_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cr")]
        public string TARGET_TYPE {
            get {
                return ((string)(this["TARGET_TYPE"]));
            }
            set {
                this["TARGET_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WARM_UP_TIME {
            get {
                return ((double)(this["WARM_UP_TIME"]));
            }
            set {
                this["WARM_UP_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DETECTOR_TYPE {
            get {
                return ((int)(this["DETECTOR_TYPE"]));
            }
            set {
                this["DETECTOR_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAVE_PATH {
            get {
                return ((string)(this["SAVE_PATH"]));
            }
            set {
                this["SAVE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAMPLE_NAME {
            get {
                return ((string)(this["SAMPLE_NAME"]));
            }
            set {
                this["SAMPLE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SAMPLE_NO {
            get {
                return ((string)(this["SAMPLE_NO"]));
            }
            set {
                this["SAMPLE_NO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MEASURE_METHOD {
            get {
                return ((int)(this["MEASURE_METHOD"]));
            }
            set {
                this["MEASURE_METHOD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PEAK_DEGREE {
            get {
                return ((double)(this["PEAK_DEGREE"]));
            }
            set {
                this["PEAK_DEGREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DEGREE_RANGE {
            get {
                return ((double)(this["DEGREE_RANGE"]));
            }
            set {
                this["DEGREE_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MEASURE_STEP {
            get {
                return ((double)(this["MEASURE_STEP"]));
            }
            set {
                this["MEASURE_STEP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MEASURE_TIME {
            get {
                return ((double)(this["MEASURE_TIME"]));
            }
            set {
                this["MEASURE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TUBE_VOLTAGE {
            get {
                return ((double)(this["TUBE_VOLTAGE"]));
            }
            set {
                this["TUBE_VOLTAGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TUBE_CURRENT {
            get {
                return ((double)(this["TUBE_CURRENT"]));
            }
            set {
                this["TUBE_CURRENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] PSI_ANGLE {
            get {
                return ((double[])(this["PSI_ANGLE"]));
            }
            set {
                this["PSI_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] X_ANGLE {
            get {
                return ((double[])(this["X_ANGLE"]));
            }
            set {
                this["X_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] Y_ANGLE {
            get {
                return ((double[])(this["Y_ANGLE"]));
            }
            set {
                this["Y_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] Z_ANGLE {
            get {
                return ((double[])(this["Z_ANGLE"]));
            }
            set {
                this["Z_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] ALPHA_ANGLE {
            get {
                return ((double[])(this["ALPHA_ANGLE"]));
            }
            set {
                this["ALPHA_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public double[] BETA_ANGLE {
            get {
                return ((double[])(this["BETA_ANGLE"]));
            }
            set {
                this["BETA_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string COM {
            get {
                return ((string)(this["COM"]));
            }
            set {
                this["COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string INI_PATH {
            get {
                return ((string)(this["INI_PATH"]));
            }
            set {
                this["INI_PATH"] = value;
            }
        }
    }
}
